#spring:
#  datasource:
#    url: jdbc:h2:mem:a5238a73-4cb5-4aff-9666-242b594436f4
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#
#logging:
#  level:
#    org.hibernate.SQL: debug

spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
